import "../styles/app.scss"
import Header from "./header.jsx"
import {ContextProvider} from "./components/Clients"
export const metadata = {
  title: 'todoapp',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     
      <body>
    <ContextProvider>
    <>
    <Header/>
    {children}
    </>
    </ContextProvider>
        </body>
    </html>
  )
}
